In [1]:
import pandas as pd
import technical_analysis as ta
%load_ext autoreload
%autoreload 2

In [41]:
# Create a dummy dataset for testing
data = {
    'DATE': pd.date_range(start='2023-01-01', periods=20, freq='D'),
    'OPEN': [100, 105, 102, 99, 98, 110, 115, 120, 125, 110, 108, 107, 106, 115, 112, 110, 100, 98, 97, 96],
    'HIGH': [110, 110, 105, 103, 100, 115, 120, 125, 130, 115, 112, 110, 108, 120, 115, 112, 105, 102, 100, 99],
    'LOW': [95, 100, 100, 95, 97, 105, 110, 118, 122, 108, 105, 103, 104, 113, 110, 108, 98, 95, 96, 94],
    'CLOSE': [105, 108, 103, 95, 99, 112, 117, 123, 127, 109, 107, 108, 106, 118, 111, 109, 102, 97, 98, 95],
}

df = pd.DataFrame(data)

In [42]:
ta_analysis = ta.CandlestickAnalyser(df)
#ta_analysis.detect_all_patterns()
data = ta_analysis.get_results()
data

         DATE  OPEN  HIGH  LOW  CLOSE
0  2023-01-01   100   110   95    105
1  2023-01-02   105   110  100    108
2  2023-01-03   102   105  100    103
3  2023-01-04    99   103   95     95
4  2023-01-05    98   100   97     99
5  2023-01-06   110   115  105    112
6  2023-01-07   115   120  110    117
7  2023-01-08   120   125  118    123
8  2023-01-09   125   130  122    127
9  2023-01-10   110   115  108    109
10 2023-01-11   108   112  105    107
11 2023-01-12   107   110  103    108
12 2023-01-13   106   108  104    106
13 2023-01-14   115   120  113    118
14 2023-01-15   112   115  110    111
15 2023-01-16   110   112  108    109
16 2023-01-17   100   105   98    102
17 2023-01-18    98   102   95     97
18 2023-01-19    97   100   96     98
19 2023-01-20    96    99   94     95

In [31]:
data.columns

Index(['DATE', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'bullish_marubuzo',
       'bearish_marubuzo', 'doji', 'hammer', 'hanging_man', 'shooting_star'],
      dtype='object')

In [33]:
#df['Single_Candlestick_pattern'] = 
pattern_columns = ['bearish_marubuzo', 'doji', 'hammer', 'hanging_man', 'shooting_star']
data_filtered = data[data[pattern_columns].any(axis=1) == True]

In [39]:
['SYMBOL']+pattern_columns

['SYMBOL',
 'bearish_marubuzo',
 'doji',
 'hammer',
 'hanging_man',
 'shooting_star']

In [34]:
data_filtered

,DATE,OPEN,HIGH,LOW,CLOSE,bullish_marubuzo,bearish_marubuzo,doji,hammer,hanging_man,shooting_star
2,2023-01-03,102,105,100,103,False,False,True,False,False,False
9,2023-01-10,110,115,108,109,False,False,True,False,False,False
10,2023-01-11,108,112,105,107,False,False,True,False,False,False
11,2023-01-12,107,110,103,108,False,False,True,False,False,False
12,2023-01-13,106,108,104,106,False,False,True,False,False,False
14,2023-01-15,112,115,110,111,False,False,True,False,False,False
15,2023-01-16,110,112,108,109,False,False,True,False,False,False

In [38]:
import pandas as pd

# Example DataFrame
data = {
    "SYMBOL": ["AAPL", "AAPL", "GOOG", "GOOG", "MSFT", "MSFT"],
    "bullish_marubuzo": [True, False, False, True, False, True],
    "bearish_marubuzo": [False, True, False, False, True, False],
    "doji": [False, False, True, False, False, False],
}

df = pd.DataFrame(data)

# Find patterns where column value is True
def find_patterns(dataframe):
    # Melt the DataFrame to make pattern names a single column
    melted = dataframe.melt(id_vars=["SYMBOL"], var_name="Pattern", value_name="Detected")
    display(melted)
    # Filter rows where Detected is True
    filtered = melted[melted["Detected"]]
    display(filtered)
    
    # Group by SYMBOL and aggregate pattern names
    grouped = filtered.groupby("SYMBOL")["Pattern"].apply(list).reset_index()
    display(grouped)
    grouped.rename(columns={"Pattern": "Detected_Patterns"}, inplace=True)
    
    return grouped

# Apply the function
result = find_patterns(df)

# Display the result
print(result)

   SYMBOL           Pattern  Detected
0    AAPL  bullish_marubuzo      True
1    AAPL  bullish_marubuzo     False
2    GOOG  bullish_marubuzo     False
3    GOOG  bullish_marubuzo      True
4    MSFT  bullish_marubuzo     False
5    MSFT  bullish_marubuzo      True
6    AAPL  bearish_marubuzo     False
7    AAPL  bearish_marubuzo      True
8    GOOG  bearish_marubuzo     False
9    GOOG  bearish_marubuzo     False
10   MSFT  bearish_marubuzo      True
11   MSFT  bearish_marubuzo     False
12   AAPL              doji     False
13   AAPL              doji     False
14   GOOG              doji      True
15   GOOG              doji     False
16   MSFT              doji     False
17   MSFT              doji     False

   SYMBOL           Pattern  Detected
0    AAPL  bullish_marubuzo      True
3    GOOG  bullish_marubuzo      True
5    MSFT  bullish_marubuzo      True
7    AAPL  bearish_marubuzo      True
10   MSFT  bearish_marubuzo      True
14   GOOG              doji      True

  SYMBOL                               Pattern
0   AAPL  [bullish_marubuzo, bearish_marubuzo]
1   GOOG              [bullish_marubuzo, doji]
2   MSFT  [bullish_marubuzo, bearish_marubuzo]

  SYMBOL                     Detected_Patterns
0   AAPL  [bullish_marubuzo, bearish_marubuzo]
1   GOOG              [bullish_marubuzo, doji]
2   MSFT  [bullish_marubuzo, bearish_marubuzo]

In [ ]:
[{"field": i,'filter':True} for i in data.columns]

[{'field': 'DATE', filter: True},
 {'field': 'OPEN', filter: True},
 {'field': 'HIGH', filter: True},
 {'field': 'LOW', filter: True},
 {'field': 'CLOSE', filter: True}]